// Code generated by "stringer -type=Axis"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[X-0]
	_ = x[Y-1]
	_ = x[Z-2]
}

const _Axis_name = "XYZ"

var _Axis_index = [...]uint8{0, 1, 2, 3}

func (i Axis) String() string {
	if i < 0 || i >= Axis(len(_Axis_index)-1) {
		return "Axis(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Axis_name[_Axis_index[i]:_Axis_index[i+1]]
}
