// Code generated by "stringer -type=SensorType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pos-0]
	_ = x[Vel-1]
}

const _SensorType_name = "PosVel"

var _SensorType_index = [...]uint8{0, 3, 6}

func (i SensorType) String() string {
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
